title: Andrew Szigethy
description: Engineering Manager, SWE & Architecture building software platforms, product systems, and engineering organizations that deliver measurable business value.
url: https://aszigethy.github.io
baseurl: /portfolio
repository: aszigethy/portfolio
timezone: America/New_York
markdown: kramdown
permalink: /blog/:slug/
future: true
exclude:
  - private
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "_posts"
    values:
      layout: post
      permalink: /blog/:slug/
      author: Andrew Szigethy
